# Numpy by KJ

In [1]:
import numpy as np

In [2]:
myarr = np.array([[6, 2, 3, 49999999, 5]], np.int64)

In [3]:
myarr[0, 1]

np.int64(2)

In [4]:
myarr.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0, 1]

np.int64(2)

In [7]:
myarr[0, 1] = 69

In [8]:
myarr[0, 1]

np.int64(69)

In [9]:
myarr

array([[       6,       69,        3, 49999999,        5]])

# 1. Array creation: conversion from other python structures

In [10]:
listArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listArray.dtype

dtype('int64')

In [13]:
listArray.shape

(3, 3)

In [14]:
listArray.size

9

In [15]:
np.array({654, 65, 298})

array({65, 298, 654}, dtype=object)

# 2. Array creation: Intrinsic NumPy array creation functions

In [16]:
zeroes = np.zeros((2, 5))

In [17]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(5)

In [19]:
rng

array([0, 1, 2, 3, 4])

In [20]:
linspace = np.linspace(1, 5, 5)

In [21]:
linspace

array([1., 2., 3., 4., 5.])

In [22]:
emp = np.empty((4, 6))

In [23]:
emp

array([[4.68590049e-310, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 9.08366793e+223,
        1.14177168e+243, 2.45126797e+198, 1.06083187e-153],
       [2.35625393e+251, 6.01334511e-154, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 1.88556770e+122],
       [4.96820036e+180, 6.80600993e+212, 1.10317376e+217,
        1.19490107e+190, 2.06642651e+161, 5.44760669e-109]])

In [24]:
emp_like = np.empty_like(linspace)

In [25]:
emp_like

array([1., 2., 3., 4., 5.])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3, 33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr.shape

(99,)

# Axis 

In [35]:
x = [[1, 24, 3], [46, 5, 6], [0, 8, 9]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[ 1, 24,  3],
       [46,  5,  6],
       [ 0,  8,  9]])

In [38]:
ar.sum(axis=0)

array([47, 37, 18])

In [39]:
ar.sum(axis=1)

array([28, 57, 17])

In [40]:
ar.T

array([[ 1, 46,  0],
       [24,  5,  8],
       [ 3,  6,  9]])

In [41]:
for i in ar.flat:
    print(i)

1
24
3
46
5
6
0
8
9


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

72

In [45]:
one = np.array([1, 2, 333, 4, 5])

In [46]:
one.argmax()

np.int64(2)

In [47]:
one.argmin()

np.int64(0)

In [48]:
one.argsort()

array([0, 1, 3, 4, 2])

In [49]:
ar

array([[ 1, 24,  3],
       [46,  5,  6],
       [ 0,  8,  9]])

In [50]:
ar.argmin()

np.int64(6)

In [51]:
ar.argmax()

np.int64(3)

In [52]:
ar.argmax(axis=0)

array([1, 0, 2])

In [53]:
ar.argmin(axis=1)

array([0, 1, 0])

In [54]:
ar.argsort(axis=0)

array([[2, 1, 0],
       [0, 2, 1],
       [1, 0, 2]])

In [55]:
ar.argsort(axis=1)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2]])

In [56]:
ar.ravel()

array([ 1, 24,  3, 46,  5,  6,  0,  8,  9])

In [57]:
ar.reshape((9, 1))

array([[ 1],
       [24],
       [ 3],
       [46],
       [ 5],
       [ 6],
       [ 0],
       [ 8],
       [ 9]])

# Mathematical Operations

In [58]:
ar

array([[ 1, 24,  3],
       [46,  5,  6],
       [ 0,  8,  9]])

In [59]:
ar2 = np.array([[ 1, 4,  3],
       [6,  5,  6],
       [ 0,  8,  9]])

In [60]:
ar + ar2

array([[ 2, 28,  6],
       [52, 10, 12],
       [ 0, 16, 18]])

In [61]:
ar * ar2

array([[  1,  96,   9],
       [276,  25,  36],
       [  0,  64,  81]])

In [62]:
np.sqrt(ar)

array([[1.        , 4.89897949, 1.73205081],
       [6.78232998, 2.23606798, 2.44948974],
       [0.        , 2.82842712, 3.        ]])

In [63]:
ar.sum()

np.int64(102)

In [64]:
ar.max()

np.int64(46)

In [65]:
ar.min()

np.int64(0)

# Finding an element

In [66]:
ar

array([[ 1, 24,  3],
       [46,  5,  6],
       [ 0,  8,  9]])

In [67]:
np.where(ar>10)

(array([0, 1]), array([1, 0]))

In [68]:
np.count_nonzero(ar)

np.int64(8)

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 1, 2]))

In [70]:
import sys

In [71]:
py_ar = [0, 1, 22, 69]

In [72]:
np_ar = np.array(py_ar)

In [73]:
sys.getsizeof(1) * len(py_ar)

112

In [74]:
np_ar.itemsize * np_ar.size

32