# Numpy by KJ

In [1]:
import numpy as np

In [19]:
myarr = np.array([[6, 2, 3, 49999999, 5]], np.int32)

In [21]:
myarr[0, 1]

np.int32(2)

In [23]:
myarr.shape

(1, 5)

In [25]:
myarr.dtype

dtype('int32')

In [26]:
myarr[0, 1]

np.int32(2)

In [27]:
myarr[0, 1] = 69

In [28]:
myarr[0, 1]

np.int32(69)

In [29]:
myarr

array([[       6,       69,        3, 49999999,        5]], dtype=int32)

# 1. Array creation: conversion from other python structures

In [31]:
listArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
listArray.dtype

dtype('int64')

In [34]:
listArray.shape

(3, 3)

In [35]:
listArray.size

9

In [36]:
np.array({654, 65, 298})

array({65, 298, 654}, dtype=object)

# 2. Array creation: Intrinsic NumPy array creation functions

In [38]:
zeroes = np.zeros((2, 5))

In [39]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
rng = np.arange(5)

In [41]:
rng

array([0, 1, 2, 3, 4])

In [57]:
linspace = np.linspace(1, 5, 5)

In [58]:
linspace

array([1., 2., 3., 4., 5.])

In [59]:
emp = np.empty((4, 6))

In [60]:
emp

array([[4.66092346e-310, 0.00000000e+000, 9.82157975e+252,
        8.89489936e+252, 6.01346954e-154, 6.01347002e-154],
       [6.01347002e-154, 6.01347002e-154, 9.08366793e+223,
        1.14177168e+243, 2.45126797e+198, 1.06083187e-153],
       [2.35625393e+251, 6.01334511e-154, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 1.88556770e+122],
       [4.96820036e+180, 6.80600993e+212, 1.10317376e+217,
        1.19490107e+190, 2.06642651e+161, 5.44760669e-109]])

In [61]:
emp_like = np.empty_like(linspace)

In [62]:
emp_like

array([1., 2., 3., 4., 5.])

In [63]:
ide = np.identity(45)

In [64]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [65]:
ide.shape

(45, 45)

In [66]:
arr = np.arange(99)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [72]:
arr = arr.reshape(3, 33)

In [73]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [76]:
arr = arr.ravel()

In [77]:
arr.shape

(99,)

# Axis 

In [79]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [80]:
ar = np.array(x)

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
ar.sum(axis=0)

array([12, 15, 18])